name: CI ReUse Main
on:
  workflow_call:
    inputs:
      appType:
        required: true
        type: string
      appName:
        required: true
        type: string
    secrets:
      vault_token:
        required: true

jobs:
  Build:
    uses: prashumps/roboshop-github-actions/.github/workflows/build.yml@main
    with:
      appType: '${{ inputs.appType }}'
      appName: '${{ inputs.appName }}'
      docker_build: false
    secrets:
      vault_token: '${{ secrets.vault_token }}'
  Test:
    needs: Build
    uses: prashumps/roboshop-github-actions/.github/workflows/test.yml@main
    with:
      appType: '${{ inputs.appType }}'
      appName: '${{ inputs.appName }}'
  DockerBuild:
    needs: Test
    uses: prashumps/roboshop-github-actions/.github/workflows/build.yml@main
    with:
        appType: '${{ inputs.appType }}'
        appName: '${{ inputs.appName }}'
        docker_build: 'true'
    secrets:
      vault_token: '${{ secrets.vault_token }}'
  Dev_Deploy:
    environment: DEV
    needs: DockerBuild
    runs-on: self-hosted
    steps:
      - run: echo OK
  Qa_Deploy:
    environment: QA
    needs: Dev_Deploy
    runs-on: self-hosted
    steps:
      - run: echo OK
  Uat_Deploy:
    environment: UAT
    needs: Qa_Deploy
    runs-on: self-hosted
    steps:
      - run: echo OK
  Prod_Deploy:
    environment: PROD
    needs: Uat_Deploy
    runs-on: self-hosted
    steps:
      - run: echo OK
