name: GitHub Runner Docker Image
on:
  workflow_dispatch:
  push:
    paths:
      - 'runner-docker-image/**'
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Docker Build
        run: |
          cd runner-docker-image
          docker build -t prasanthreddymps/github-runner .
