name: Test Cases
on:
  workflow_call:
    inputs:
      appType:
        required: true
        type: string
      appName:
        required: true
        type: string

jobs:
  NodeJS_Test:
    if: ${{ inputs.appType == 'nodejs' }}
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v5
      - run: | 
          echo npm install
          echo npm test
        name: Download dependencies

  Maven_Test:
    if: ${{ inputs.appType == 'maven' }}
    runs-on: self-hosted
    steps:
      - run: echo mvn test

  Python_Test:
    if: ${{ inputs.appType == 'python' }}
    runs-on: self-hosted
    steps:
      - run: echo python -m unittest
